name: Pong Firmware Dumper

on:
  workflow_dispatch:
    inputs:
      urls:
        description: 'URLs'
        required: true
      name:
        description: 'Name'
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Cache apt packages
      uses: actions/cache@v3
      with:
        path: /var/cache/apt
        key: ${{ runner.os }}-apt-${{ hashFiles('**/setup.sh') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Setup system dependencies
      run: |
        sudo apt update
        sudo apt -y install aria2 zstd p7zip-full parallel openssl xxhash

    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install gdown
      run: |
        python3 -m pip install gdown

  dump:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        url: ${{ fromJson(inputs.urls) }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set script permissions
      run: |
        chmod +x dump.sh

    - name: Dump
      id: dump
      run: ./dump.sh ${{ matrix.url }}

    - name: Upload release assets
      uses: ncipollo/release-action@v1
      with:
        artifacts: out/*
        artifactErrorsFailBuild: true
        body: ${{ steps.dump.outputs.body }}
        tag: ${{ github.event.inputs.name }}
        token: ${{ secrets.GITHUB_TOKEN }}
